<script setup lang="ts">
import {ref,computed,onMounted,onUnmounted,nextTick} from 'vue';
import {LayoutDashboard,Boxes,Globe2,Settings2,Play,Square,Terminal,RefreshCw,ArrowUpRight,Download,Search,Plus,Check,ChevronRight,Users,Radio,Wifi,Server,FolderOpen,LoaderCircle,Save,X,Copy,ExternalLink,Menu,Clock3,Leaf,ShieldCheck} from 'lucide-vue-next';
import WorldArt from './WorldArt.vue';
import WorldBadge from './WorldBadge.vue';
import ServerConfig from './ServerConfig.vue';
import PlayersPanel from './PlayersPanel.vue';
import type {AppState,Settings,LogEntry} from '../shared/types';
const state=ref<AppState>(),page=ref('overview'),loading=ref(true),failure=ref(''),submitting=ref(false),connected=ref(false),mobileMenu=ref(false);
const draft=ref<string[]>([]),revision=ref(''),form=ref<Settings>(),world=ref(''),query=ref(''),filter=ref('all'),input=ref(''),paused=ref(false),consoleEl=ref<HTMLElement>();
const modal=ref<'start'|'create'|null>(null),newName=ref(''),newSize=ref(1),newDifficulty=ref(1),newSeed=ref('');
const toast=ref<{text:string,error:boolean}|null>(null),now=ref(new Date());
const nav=[{id:'overview',name:'服务器概览',icon:LayoutDashboard},{id:'mods',name:'Mod 管理',icon:Boxes},{id:'worlds',name:'世界管理',icon:Globe2},{id:'config',name:'服务器配置',icon:Server},{id:'players',name:'用户管理',icon:Users},{id:'settings',name:'工具设置',icon:Settings2}];
const selectedId=ref(''),marked=ref<string[]>([]),launchPort=ref(7777);
const current=computed(()=>state.value?.instances.find(i=>i.config.id===selectedId.value)||state.value?.instances[0]);
const currentLogs=computed(()=>state.value?.logs.filter(l=>!l.instanceId||l.instanceId===current.value?.config.id)||[]);
const canStart=computed(()=>!submitting.value&&!state.value?.busy&&!active.value&&status.value!=='external');
function selectInstance(id:string){selectedId.value=id;world.value=current.value?.config.world||state.value?.worlds[0]?.name||'';launchPort.value=current.value?.config.port||7777;}
function batch(enable:boolean){const selected=state.value?.mods.filter(m=>marked.value.includes(m.name)&&m.path&&m.compatible&&!m.error).map(m=>m.name)||[];draft.value=enable?[...new Set([...draft.value,...selected])]:draft.value.filter(n=>!selected.includes(n));}
function allVisible(){const names=mods.value.map(m=>m.name);marked.value=names.every(n=>marked.value.includes(n))?marked.value.filter(n=>!names.includes(n)):[...new Set([...marked.value,...names])];}
const title=computed(()=>nav.find(n=>n.id===page.value)?.name||'服务器概览');
const URL = globalThis.URL;
const labels:Record<string,string>={stopped:'未运行',starting:'启动中',running:'运行中',stopping:'关闭中',error:'需要处理',external:'外部占用'};
const status=computed(()=>current.value?.server.state||'stopped');
const active=computed(()=>!!current.value?.server.pid);
const locked=computed(()=>submitting.value||!!state.value?.busy||!!state.value?.instances.some(i=>i.server.pid)||status.value==='external');
const dirty=computed(()=>JSON.stringify([...draft.value].sort())!==JSON.stringify([...(state.value?.enabled||[])].sort()));
const formDirty=computed(()=>!!form.value&&JSON.stringify(form.value)!==JSON.stringify(state.value?.settings));
const mods=computed(()=>(state.value?.mods||[]).filter(m=>(!query.value||`${m.name} ${m.displayName} ${m.author}`.toLowerCase().includes(query.value.toLowerCase()))&&(filter.value==='all'||(filter.value==='enabled'?draft.value.includes(m.name):!draft.value.includes(m.name)))));
const clock=computed(()=>now.value.toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}));
const uptime=computed(()=>{const time=current.value?.server.startedAt;if(!active.value||!time)return '尚未启动';const minutes=Math.max(0,Math.floor((now.value.getTime()-new Date(time).getTime())/60000));return minutes<60?`${minutes} 分钟`:`${Math.floor(minutes/60)} 小时 ${minutes%60} 分钟`;});
let events:EventSource|undefined,timer:ReturnType<typeof setInterval>,toastTimer:ReturnType<typeof setTimeout>;
function notify(text:string,error=false){toast.value={text,error};clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.value=null,6500);}
async function request(url:string,method='GET',body?:unknown){const response=await fetch('/api'+url,{method,headers:method==='GET'?{}:{'Content-Type':'application/json','X-Tmod-Tools':'1'},body:body===undefined?undefined:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error||'请求失败');return result;}
async function load(preserve=true){try{const data=await request('/state');const keep=preserve&&dirty.value,keepForm=preserve&&formDirty.value;state.value=data;if(!keep){draft.value=[...data.enabled];revision.value=data.revision;}if(!keepForm)form.value={...data.settings};if(!selectedId.value)selectInstance(data.instances[0]?.config.id||'');if(!world.value)world.value=data.worlds[0]?.name||'';failure.value='';}catch(e:any){failure.value=e.message;}finally{loading.value=false;}}
async function act(url:string,body:unknown,success:string,method='POST'){
  submitting.value=true;
  try{await request(url,method,body);notify(success);await load();return true;}catch(e:any){notify(e.message,true);return false;}finally{submitting.value=false;}
}
async function saveMods(){if(await act('/mods',{names:draft.value,revision:revision.value},'启用列表已保存，下次启动生效','PUT'))await load(false);}
async function download(){if(await act('/downloads',{input:input.value.trim()},'已加入下载队列'))input.value='';}
async function saveSettings(){if(await act('/settings',form.value,'设置已保存','PUT'))form.value={...state.value!.settings};}
function chooseWorld(name:string){const existing=state.value?.instances.find(i=>i.config.world===name);if(existing)selectInstance(existing.config.id);world.value=name;launchPort.value=existing?.config.port||Math.max(7776,...(state.value?.instances.map(i=>i.config.port)||[]))+1;modal.value='start';}
async function start(){const create=modal.value==='create',name=create?newName.value.trim():world.value;
  submitting.value=true;try{let instance=state.value?.instances.find(i=>i.config.port===launchPort.value);
    if(!instance){const data=await request('/instances','POST',{name,world:name,port:launchPort.value});instance=data.instances.find((i:any)=>i.config.port===launchPort.value);}
    await request('/instances/'+instance!.config.id+'/start','POST',{world:name,create,worldSize:newSize.value,difficulty:newDifficulty.value,seed:newSeed.value});
    selectedId.value=instance!.config.id;world.value=name;modal.value=null;page.value='overview';notify('启动请求已提交');await load();
  }catch(e:any){notify(e.message,true);}finally{submitting.value=false;}}
function instanceAction(action:string){return act('/instances/'+current.value?.config.id+'/'+action,{},action==='save'?'已发送保存命令':'正在保存并关闭');}
async function copy(text:string){try{if(navigator.clipboard&&window.isSecureContext)await navigator.clipboard.writeText(text);else{const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();document.execCommand('copy');t.remove();}notify('地址已复制');}catch{notify('复制失败，请手动复制地址',true);}}
function goto(id:string){page.value=id;mobileMenu.value=false;}
function time(value:string){return new Date(value).toLocaleTimeString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});}
function date(value:string){return new Date(value).toLocaleDateString('zh-CN',{timeZone:'Asia/Shanghai'});}
function bytes(size:number){return `${(size/1024/1024).toFixed(1)} MB`;}
function initials(name:string){return name.replace(/\[[^\]]*\]/g,'').trim().slice(0,2).toUpperCase();}
onMounted(async()=>{
  await load(false);events=new EventSource('/api/events');events.onopen=()=>{connected.value=true;void load();};events.onerror=()=>connected.value=false;
  events.addEventListener('status',e=>{if(!state.value)return;const d=JSON.parse(e.data);const changed=JSON.stringify(state.value.downloads.map(j=>j.status))!==JSON.stringify(d.downloads.map((j:any)=>j.status));const ended=state.value.server.state!==d.server.state&&['stopped','running'].includes(d.server.state);state.value.server=d.server;state.value.instances=d.instances;state.value.downloads=d.downloads;state.value.busy=d.busy;if(changed||ended)void load();});
  events.addEventListener('log',async e=>{if(!state.value)return;const entry:LogEntry=JSON.parse(e.data);if(!state.value.logs.some(l=>l.id===entry.id))state.value.logs.push(entry);if(state.value.logs.length>400)state.value.logs.shift();await nextTick();if(!paused.value&&consoleEl.value)consoleEl.value.scrollTop=consoleEl.value.scrollHeight;});
  timer=setInterval(()=>now.value=new Date(),1000);
});
onUnmounted(()=>{events?.close();clearInterval(timer);clearTimeout(toastTimer);});
</script>

<template>
  <div class="app-shell">
    <button v-if="mobileMenu" class="nav-shade" aria-label="关闭导航" @click="mobileMenu=false"></button>
    <aside class="sidebar" :class="{open:mobileMenu}">
      <a class="brand" href="#" @click.prevent="goto('overview')"><span class="brand-mark"><Leaf :size="25"/></span><span>泰拉控制台<small>TMODLOADER TOOLS</small></span></a>
      <div class="workspace-tag"><span class="mini-dot"></span>我的本地服务器<span class="tag">LOCAL</span></div>
      <div class="nav-caption">工作空间</div>
      <nav aria-label="主导航"><button v-for="item in nav" :key="item.id" :class="{selected:page===item.id}" @click="goto(item.id)"><component :is="item.icon" :size="19"/><span>{{item.name}}</span><span v-if="item.id==='mods'" class="nav-count">{{state?.mods.length||0}}</span></button></nav>
      <div class="sidebar-bottom"><div class="local-card"><Wifi :size="18"/><div>局域网共享<small>在家中的任何设备上管理</small></div><span class="online-dot"></span></div><div class="sidebar-footer"><span class="avatar">F</span><div>家庭服务器<small>Windows · 本地部署</small></div><ShieldCheck :size="16"/></div></div>
    </aside>
    <main>
      <header class="topbar"><div class="breadcrumb"><button class="icon-button mobile-toggle" aria-label="打开导航" @click="mobileMenu=true"><Menu :size="20"/></button><span>工作空间</span><ChevronRight :size="14"/><strong>{{title}}</strong></div><div class="top-meta"><span class="connection"><i :class="connected?'online-dot':'offline-dot'"></i>{{connected?'实时连接':'正在连接'}}</span><span class="top-divider"></span><Clock3 :size="14"/><span class="clock">{{clock}} <small>北京时间</small></span></div></header>
      <div v-if="loading" class="loading-state"><LoaderCircle class="spin" :size="32"/><h2>正在连接你的泰拉世界</h2><p>读取世界、Mod 与服务器状态…</p></div>
      <div v-else-if="!state" class="loading-state"><Server :size="36"/><h2>暂时无法连接管理服务</h2><p>{{failure}}</p><button class="primary" @click="load(false)">重新连接</button></div>
      <div v-else class="page-wrap">
        <div v-if="!connected" class="notice warning"><Radio :size="16"/>实时连接中断，正在自动重连；操作结果以服务器返回为准。</div>
        <div v-if="page!=='config'" class="instance-switch"><span><Server :size="16"/>当前服务器</span><select :value="current?.config.id" aria-label="当前服务器实例" @change="selectInstance(($event.target as HTMLSelectElement).value)"><option v-for="i in state.instances" :value="i.config.id">{{i.config.name}} · :{{i.config.port}} · {{labels[i.server.state]}}</option></select><button class="text-button" @click="goto('config')">管理实例<ArrowUpRight :size="14"/></button></div>
        <Transition name="page" mode="out-in">
          <section v-if="page==='overview'" key="overview">
            <div class="page-heading"><div><div class="eyebrow">YOUR WORLD, UNDER CONTROL</div><h1>服务器概览</h1><p>准备好下一场冒险了吗？你的世界，尽在掌握。</p></div><button class="secondary small" @click="load()"><RefreshCw :size="15"/>刷新状态</button></div>
            <div class="hero">
              <WorldArt/>
              <div class="hero-content"><div class="hero-label"><span class="mini-dot"></span>TMODLOADER · {{state.version}}</div><h2>你的世界，<br><em>随时启程。</em></h2><p>熟悉的像素世界，新的无限可能。<br>选好世界与 Mod，和朋友一起出发。</p><button class="primary" :disabled="!canStart||!world" @click="launchPort=current?.config.port||7777;modal='start'"><Play :size="16" fill="currentColor"/>启动服务器<ArrowUpRight :size="16"/></button><span class="hero-note">{{active?'服务器已启动，请在下方管理':'存档就在本机，冒险随时继续'}}</span></div>
              <div class="hero-caption"><span class="online-dot"></span>属于你们的冒险世界 <span>01 / ∞</span></div>
            </div>
            <div class="metrics"><div class="metric"><span class="metric-icon mint"><Server/></span><div><small>服务器状态</small><strong class="status-text" :class="status">{{labels[status]}}</strong><span>{{active?`运行时长 · ${uptime}`:'等待下一次冒险'}}</span></div></div><div class="metric"><span class="metric-icon violet"><Boxes/></span><div><small>已启用 Mod</small><strong>{{state.enabled.length}}<em>/ {{state.mods.length}}</em></strong><span>共享本机 Mod 配置</span></div></div><div class="metric"><span class="metric-icon amber"><Globe2/></span><div><small>我的世界</small><strong>{{state.worlds.length}}<em>个</em></strong><span>本地世界存档</span></div></div><div class="metric"><span class="metric-icon blue"><Users/></span><div><small>在线玩家</small><strong>{{current?.bridge==='ready'?current.players.length:'—'}}<em>/ {{current?.config.maxPlayers}}</em></strong><span>游戏端口 · {{current?.config.port}}</span></div></div></div>
            <div class="overview-grid">
              <section class="panel control-panel"><div class="panel-heading"><h3><Radio :size="17"/>服务器控制</h3><span class="status-pill" :class="status"><i></i>{{labels[status]}}</span></div><label class="field-label" for="world-select">当前世界</label><div class="world-select"><Globe2 :size="19"/><select id="world-select" v-model="world" :disabled="!canStart"><option value="" disabled>请选择世界</option><option v-for="w in state.worlds" :value="w.name">{{w.name}}</option></select></div><div class="connection-address"><span>游戏连接地址</span><button @click="copy((state.urls[0]?new URL(state.urls[0]).hostname:'127.0.0.1')+':'+current?.config.port)">{{state.urls[0]?new URL(state.urls[0]).hostname:'127.0.0.1'}}:{{current?.config.port}}<Copy :size="13"/></button></div><p class="server-message">{{current?.server.message}}</p><div class="button-row"><button v-if="!active" class="primary" :disabled="!canStart||!world" @click="launchPort=current?.config.port||7777;modal='start'"><Play :size="15"/>启动服务器</button><template v-else><button class="secondary" :disabled="status!=='running'||submitting" @click="instanceAction('save')"><Save :size="15"/>保存世界</button><button class="danger-outline" :disabled="status==='stopping'||submitting" @click="instanceAction('stop')"><Square :size="13"/>保存并关闭</button></template><button class="icon-button" title="服务器设置" aria-label="服务器设置" @click="goto('config')"><Settings2 :size="18"/></button></div></section>
              <section class="panel recent-worlds"><div class="panel-heading"><h3><Globe2 :size="17"/>我的世界</h3><button class="text-button" @click="goto('worlds')">查看全部<ArrowUpRight :size="14"/></button></div><button v-for="(w,i) in state.worlds.slice(0,3)" :key="w.name" class="world-row" @click="world=w.name;goto('worlds')"><span class="world-thumb" :class="`thumb-${i%3}`"><WorldBadge :evil="w.evil||'unknown'" :size="44"/></span><span class="world-description"><strong>{{w.name}}</strong><small>{{w.hasModData?'Mod 世界':'普通世界'}} <b>·</b> {{bytes(w.size)}} <b>·</b> {{date(w.modified)}}</small></span><ChevronRight :size="17"/></button><div v-if="!state.worlds.length" class="empty-mini">还没有世界，创建一个开始冒险。</div></section>
            </div>
            <section class="panel online-preview"><div class="panel-heading"><h3><Users :size="17"/>在线用户</h3><button class="text-button" @click="goto('players')">用户管理<ArrowUpRight :size="14"/></button></div><div v-if="current?.bridge==='ready'" class="player-chips"><span v-for="p in current.players" :key="p.slot"><i class="online-dot"></i>{{p.name}} <small>{{p.life}} / {{p.maxLife}} HP</small></span><p v-if="!current.players.length" class="muted">当前没有在线玩家，等朋友们加入冒险。</p></div><p v-else class="muted">{{status==='running'?'正在连接玩家管理模块…':'服务器启动后显示在线玩家'}}</p></section>
            <section class="panel console-panel"><div class="panel-heading"><h3><Terminal :size="17"/>实时控制台<span class="subtle-label">LIVE LOGS</span></h3><button class="text-button" @click="paused=!paused">{{paused?'恢复滚动':'暂停滚动'}}</button></div><div ref="consoleEl" class="console" role="log" aria-label="服务器日志"><div v-if="!state.logs.length" class="console-empty">等待服务器日志…</div><div v-for="entry in currentLogs" :key="entry.id" class="log-line" :class="entry.level"><time>{{time(entry.time)}}</time><span class="log-level">{{entry.level==='error'?'ERROR':entry.level==='success'?'READY':'INFO'}}</span><span>{{entry.text}}</span></div></div><div class="console-footer"><span><i class="mini-dot"></i>日志时间 · 北京时间</span><span>保留最近 400 条</span></div></section>
          </section>
          <section v-else-if="page==='mods'" key="mods">
            <div class="page-heading"><div><div class="eyebrow">BUILD YOUR ADVENTURE</div><h1>Mod 管理 <span class="heading-count">{{state.mods.length}}</span></h1><p>组合你喜欢的玩法，让每一场冒险都与众不同。</p></div><button class="secondary small" @click="load()"><RefreshCw :size="15"/>重新扫描</button></div>
            <section class="download-panel"><span class="download-emblem"><Download :size="25"/></span><div class="download-copy"><h3>从 Steam 创意工坊添加</h3><p>粘贴 Mod 链接或工坊 ID，直接下载到本机。</p></div><form class="download-form" @submit.prevent="download"><input v-model="input" aria-label="Steam 创意工坊链接" placeholder="https://steamcommunity.com/sharedfiles/…" :disabled="locked"><button class="primary" :disabled="locked||!input.trim()"><Download :size="16"/>下载 Mod</button></form></section>
            <div v-if="state.downloads.length" class="download-jobs"><div v-for="job in [...state.downloads].reverse().slice(0,5)" :key="job.id" class="download-job"><LoaderCircle v-if="['queued','downloading','installing'].includes(job.status)" class="spin" :size="17"/><Check v-else-if="job.status==='complete'" class="mint-text" :size="17"/><X v-else class="red-text" :size="17"/><div><strong>{{job.title}}</strong><p>{{job.message}}</p></div><span class="subtle-label">{{({queued:'排队中',downloading:'下载中',installing:'安装中',complete:'已完成',failed:'失败'})[job.status]}}</span><button v-if="job.status==='failed'" class="text-button" :disabled="locked" @click="input=job.id;download()">重试</button></div></div>
            <div class="notice"><ShieldCheck :size="16"/><span>与本机游戏共用配置。保存后在下次启动生效；运行游戏或服务端时不能修改。</span></div>
            <div class="list-toolbar"><div class="tabs"><button v-for="f in [{id:'all',name:'全部 Mod'},{id:'enabled',name:'已启用'},{id:'disabled',name:'未启用'}]" :class="{active:filter===f.id}" @click="filter=f.id">{{f.name}}<span v-if="f.id==='all'">{{state.mods.length}}</span></button></div><div class="search-field"><Search :size="16"/><input v-model="query" aria-label="搜索 Mod" placeholder="搜索名称、作者…"></div></div>
            <div class="batch-toolbar"><button class="secondary small" :disabled="locked" @click="allVisible">选择 / 取消当前结果</button><span>已选 {{marked.length}} 项</span><button class="secondary small" :disabled="locked||!marked.length" @click="batch(true)">批量启用</button><button class="secondary small" :disabled="locked||!marked.length" @click="batch(false)">批量关闭</button><button class="text-button" @click="marked=[]">清空选择</button></div><div class="mod-grid"><article v-for="(m,i) in mods" :key="m.name" class="mod-card" :class="{enabled:draft.includes(m.name),invalid:!m.compatible||m.error}"><div class="mod-card-top"><input class="row-check" type="checkbox" v-model="marked" :value="m.name" :aria-label="`选择 ${m.displayName}`" :disabled="locked"><span class="mod-avatar" :class="`color-${i%5}`">{{initials(m.displayName)}}</span><label class="toggle"><input type="checkbox" v-model="draft" :value="m.name" :aria-label="`启用 ${m.displayName}`" :disabled="locked||!m.path||(!draft.includes(m.name)&&(!m.compatible||!!m.error))"><span></span></label></div><h3 :title="m.displayName">{{m.displayName}}</h3><p class="mod-author">{{m.author||m.name}}</p><div class="mod-meta"><span>v{{m.version}}</span><span>{{m.source}}</span><a v-if="m.workshopId" :href="`https://steamcommunity.com/sharedfiles/filedetails/?id=${m.workshopId}`" target="_blank" rel="noreferrer" :aria-label="`在 Steam 查看 ${m.displayName}`"><ExternalLink :size="13"/></a></div><p v-if="m.error||!m.compatible" class="mod-error">{{m.error||'与当前 tModLoader 不兼容'}}</p><div v-else class="mod-foot"><span :class="draft.includes(m.name)?'mint-text':''"><i :class="draft.includes(m.name)?'mini-dot':'muted-dot'"></i>{{draft.includes(m.name)?'已启用':'未启用'}}</span><span :title="m.dependencies.join('、')">{{m.dependencies.length?`${m.dependencies.length} 项依赖`:'无额外依赖'}} · {{m.side===1?'客户端':'服务端可用'}}</span></div></article></div>
            <div v-if="!mods.length" class="empty-state"><Search :size="28"/><h3>没有找到匹配的 Mod</h3><p>换个关键词，或从创意工坊添加新的 Mod。</p></div>
            <div class="save-bar"><div><strong>{{draft.length}} 个 Mod 已选择</strong><span>{{dirty?'有尚未保存的变更':'启用列表已与本机同步'}}</span></div><div class="button-row"><button class="secondary" :disabled="!dirty||submitting" @click="load(false)">撤销修改</button><button class="primary" :disabled="locked||!dirty" @click="saveMods"><Save :size="16"/>保存启用列表</button></div></div>
          </section>
          <section v-else-if="page==='worlds'" key="worlds">
            <div class="page-heading"><div><div class="eyebrow">A PLACE TO CALL HOME</div><h1>世界管理</h1><p>继续熟悉的旅程，或者创造一片全新的天地。</p></div><button class="primary small" :disabled="submitting||state.busy||status==='external'" @click="launchPort=Math.max(7776,...state.instances.map(i=>i.config.port))+1;modal='create'"><Plus :size="17"/>创建世界</button></div>
            <div class="world-grid"><article v-for="(w,i) in state.worlds" :key="w.name" class="world-card" :class="{chosen:world===w.name}"><div class="world-cover" :class="w.evil"><WorldBadge :evil="w.evil||'unknown'" :size="138"/><span class="cover-badge">{{w.evil==='crimson'?'猩红世界':w.evil==='corruption'?'腐化 · 暗影世界':'未知世界类型'}}</span><span class="world-difficulty">{{w.sizeLabel}} · {{['经典','专家','大师','旅行'][w.difficulty??-1]||'未知难度'}}</span></div><div class="world-card-body"><h3>{{w.name}}</h3><p>{{bytes(w.size)}}<span>最后保存 {{date(w.modified)}}</span></p><div class="world-card-bottom"><span :class="w.hasModData?'mint-text':''"><ShieldCheck :size="14"/>{{w.hasModData?'配套 Mod 存档':'本地存档'}}</span><button class="secondary small" :disabled="submitting||state.busy||!!state.instances.find(i=>i.config.world===w.name&&i.server.pid)||status==='external'" @click="chooseWorld(w.name)"><Play :size="13"/>启动此世界</button></div></div></article></div>
            <div v-if="!state.worlds.length" class="empty-state"><Globe2 :size="36"/><h3>这个目录还没有世界</h3><p>创建新世界，或在工具设置中检查存档目录。</p></div>

          </section>
          <ServerConfig v-else-if="page==='config'" key="config" :state="state" :selected-id="current?.config.id||''" @refresh="load()" @select="selectInstance" @notify="notify"/>
          <PlayersPanel v-else-if="page==='players'" key="players" :instance="current"/>
          <section v-else key="settings">
            <div class="page-heading"><div><div class="eyebrow">MADE FOR YOUR SETUP</div><h1>工具设置</h1><p>本机运行，局域网共享。让每一项配置都有迹可循。</p></div><span class="version-tag">v1.1.0</span></div>
            <section class="panel settings-panel" v-if="form"><div class="panel-heading"><h3><FolderOpen :size="18"/>安装与存档目录</h3><span class="status-pill running"><i></i>本地文件</span></div><form @submit.prevent="saveSettings"><div class="form-grid"><label class="full-width">tModLoader 安装目录<input v-model="form.installDir" class="mono" :disabled="locked"><small>包含 tModLoader.dll 和自带 .NET 环境的目录。</small></label><label class="full-width">共用存档根目录<input v-model="form.saveDir" class="mono" :disabled="locked"><small>此目录下的 Worlds、Mods、ModConfigs 会与本机游戏共用。</small></label><label class="full-width">Steam 工坊 Mod 目录<input v-model="form.workshopDir" class="mono" :disabled="locked"><small>通常以 steamapps\workshop\content\1281930 结尾。</small></label></div><div class="form-footer"><span>更换目录前请先关闭游戏和服务端。</span><button class="primary" :disabled="locked"><Save :size="16"/>保存路径</button></div></form></section>
            <div class="settings-columns"><section class="panel settings-panel"><div class="panel-heading"><h3><Wifi :size="18"/>局域网访问</h3></div><p class="muted">同一局域网的手机或电脑，打开以下地址即可管理。</p><button v-for="url in state.urls" class="url-row" @click="copy(url)"><span>{{url}}</span><Copy :size="15"/></button><div class="setting-row"><span>管理登录</span><strong>无需密码</strong></div><div class="setting-row"><span>网页端口</span><strong>{{state.settings.webPort}}</strong></div></section><section class="panel settings-panel"><div class="panel-heading"><h3><Clock3 :size="18"/>运行环境</h3></div><div class="setting-row"><span>tModLoader</span><strong>{{state.version}}</strong></div><div class="setting-row"><span>平台</span><strong>Windows · 64 位</strong></div><div class="setting-row"><span>统一时区</span><strong>中国标准时间</strong></div><div class="setting-row"><span>北京时间</span><strong class="mono">{{clock}}</strong></div></section></div>
          </section>
        </Transition>
        <footer class="page-footer"><span><Leaf :size="13"/>泰拉控制台 <b>·</b> 为每一次冒险做好准备</span><span>本地运行 <b>·</b> 数据由你掌握</span></footer>
      </div>
    </main>
    <Transition name="toast"><div v-if="toast" class="toast" :class="{error:toast.error}" role="status"><X v-if="toast.error" :size="19"/><Check v-else :size="19"/><span>{{toast.text}}</span><button class="icon-button" aria-label="关闭消息" @click="toast=null"><X :size="15"/></button></div></Transition>
    <Transition name="modal"><div v-if="modal" class="modal-backdrop" @click.self="!submitting&&(modal=null)" @keydown.esc="!submitting&&(modal=null)"><section class="modal-card" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="panel-heading"><h2 id="modal-title">{{modal==='create'?'创造新的世界':'准备开始冒险'}}</h2><button class="icon-button" :disabled="submitting" aria-label="关闭" @click="modal=null"><X :size="20"/></button></div><form @submit.prevent="start"><template v-if="modal==='create'"><label>世界名称<input v-model="newName" required maxlength="100" autofocus placeholder="给新世界起个名字"></label><div class="form-grid"><label>世界大小<select v-model="newSize"><option :value="1">小型世界</option><option :value="2">中型世界</option><option :value="3">大型世界</option></select></label><label>世界难度<select v-model="newDifficulty"><option :value="0">经典</option><option :value="1">专家</option><option :value="2">大师</option><option :value="3">旅行</option></select></label></div><label>世界种子<input v-model="newSeed" placeholder="留空使用随机种子" maxlength="100"></label><p class="muted">使用当前 {{state?.enabled.length}} 个启用项生成世界，完成后启动服务器。不会覆盖现有地图。</p></template><template v-else><div class="start-world"><Globe2 :size="28"/><div><strong>{{world}}</strong><span>{{state?.enabled.length}} 个启用项 · 端口 {{launchPort}}</span></div></div><p class="muted">即将加载这个世界。请勿同时在本机游戏中打开同一个世界，避免存档冲突。</p></template><label>游戏连接端口<input v-model.number="launchPort" type="number" min="1024" max="65535" required></label><p class="muted">不同世界使用不同端口；所有世界共用 Mod 启用列表。</p><div class="modal-actions"><button type="button" class="secondary" :disabled="submitting" @click="modal=null">取消</button><button class="primary" :disabled="submitting||state?.busy||status==='external'"><LoaderCircle v-if="submitting" class="spin" :size="16"/><Play v-else :size="15"/>{{modal==='create'?'创建并启动':'启动服务器'}}</button></div></form></section></div></Transition>
  </div>
</template>
